/* Shared demo data for all pages. Data shape mirrors the Flask/Jinja
   context so an engineer can map it 1:1 back to templates. */
window.DEMO = {
  meta: {
    today: "2026-04-20",
    queueTotal: 14,
    queueByStatus: { "Skim Later": 6, "Deep Read": 5, "Reading": 2, "Archived": 1 },
    liked: 47,
    collections: 9,
    subscriptions: 6,
    jobStatus: "fresh",
    jobRun: "06:12 · auto",
  },

  // ---- Inbox (today's candidates) ----
  inboxFilters: [
    { id: "all",        label: "All",         count: 32 },
    { id: "untriaged",  label: "Untriaged",   count: 18 },
    { id: "relevant",   label: "Relevant",    count: 9  },
    { id: "queued",     label: "Queued",      count: 5  },
    { id: "ignored",    label: "Ignored",     count: 0  },
  ],
  inboxDates: [
    { d: "Apr 20", w: "Sun", key: "2026-04-20", active: true,  count: 32 },
    { d: "Apr 19", w: "Sat", key: "2026-04-19", active: false, count: 28 },
    { d: "Apr 18", w: "Fri", key: "2026-04-18", active: false, count: 41 },
    { d: "Apr 17", w: "Thu", key: "2026-04-17", active: false, count: 36 },
    { d: "Apr 16", w: "Wed", key: "2026-04-16", active: false, count: 22 },
    { d: "Apr 15", w: "Tue", key: "2026-04-15", active: false, count: 29 },
    { d: "Apr 14", w: "Mon", key: "2026-04-14", active: false, count: 33 },
  ],
  inboxThemes: [
    "conformal prediction", "covariate shift", "double descent",
    "causal inference", "Bayesian deep learning", "sequential testing"
  ],
  papers: [
    {
      id: "p1",
      rank: 1,
      score: 9.4,
      title: "Adaptive Conformal Prediction under Heavy Covariate Shift with Finite-Sample Guarantees",
      authors: "Y. Romano, L. Chen, A. Angelopoulos, E. J. Candès",
      venue: "arXiv · stat.ML",
      date: "Apr 20",
      summary: "We extend split conformal prediction to settings with severe covariate shift, proving distribution-free finite-sample coverage without requiring density ratio estimation. The method uses a self-calibrating reweighting scheme and maintains validity with n as small as 200.",
      tags: ["conformal", "covariate shift", "uncertainty"],
      reasons: [
        { text: "Matches subscription 'finite-sample conformal under shift'", where: "title", impact: "+3.2" },
        { text: "Author Y. Romano is followed", where: "author", impact: "+1.6" },
        { text: "Three words from your Library notes on CP", where: "abstract", impact: "+0.8" },
      ],
      status: "inbox",
    },
    {
      id: "p2",
      rank: 2,
      score: 8.7,
      title: "Double Descent is Not a Phenomenon of Overparametrization: A Bias-Variance Decomposition",
      authors: "D. Yang, T. Hastie, R. Tibshirani",
      venue: "arXiv · stat.ML",
      date: "Apr 20",
      summary: "We decompose generalization error into bias, variance, and sample-size effects, showing that apparent double descent reflects non-monotone variance under mis-specification rather than overparametrization per se.",
      tags: ["bias-variance", "overparam", "stat learning"],
      reasons: [
        { text: "Author T. Hastie is followed", where: "author", impact: "+1.8" },
        { text: "Matches keyword 'double descent'", where: "title", impact: "+2.1" },
      ],
      status: "inbox",
    },
    {
      id: "p3", rank: 3, score: 8.1,
      title: "Post-Selection Inference for Bayesian Neural Networks via Randomized Response",
      authors: "J. Taylor, V. Rockova, M. Zaffran",
      venue: "arXiv · stat.ME",
      date: "Apr 20",
      summary: "Proposes a randomization mechanism enabling valid confidence intervals for BNN posteriors after model selection, bridging selective inference and variational approximation.",
      tags: ["post-selection", "Bayesian", "variational"],
      reasons: [
        { text: "Co-author J. Taylor is followed", where: "author", impact: "+1.4" },
        { text: "Related to Library 'Selective Inference' (12 papers)", where: "collection", impact: "+1.2" },
      ],
      status: "skim",
    },
    {
      id: "p4", rank: 4, score: 7.6,
      title: "Minimax Rates for Nonparametric Regression with Dependent Covariates",
      authors: "R. Samworth, S. Balakrishnan, A. Tsybakov",
      venue: "arXiv · math.ST",
      date: "Apr 20",
      summary: "Establishes sharp minimax rates for nonparametric regression when the design has long-range temporal dependence, closing a gap between i.i.d. and mixing settings.",
      tags: ["minimax", "nonparametric", "dependence"],
      reasons: [{ text: "Keyword 'minimax rates' matched", where: "title", impact: "+2.4" }],
      status: "inbox",
    },
    {
      id: "p5", rank: 5, score: 7.2,
      title: "Calibrating Large Language Models via Isotonic Conformal Recalibration",
      authors: "S. Bates, A. Fisch, R. Barber",
      venue: "arXiv · cs.LG",
      date: "Apr 20",
      summary: "Combines isotonic regression with conformal prediction to recalibrate LLM confidence scores on multi-choice tasks, with finite-sample coverage guarantees.",
      tags: ["LLM", "calibration", "conformal"],
      reasons: [
        { text: "Matches keyword 'conformal'", where: "title", impact: "+2.1" },
        { text: "Rina Barber is followed", where: "author", impact: "+1.5" },
      ],
      status: "inbox",
    },
    {
      id: "p6", rank: 6, score: 6.9,
      title: "Efficient Sequential Testing with E-values under Adversarial Sampling",
      authors: "A. Ramdas, W. Wang, L. Wasserman",
      venue: "arXiv · math.ST", date: "Apr 20",
      summary: "Studies e-value sequential tests under adversarial arm selection, achieving Type I error control with optimal stopping times.",
      tags: ["e-values", "sequential", "adversarial"],
      reasons: [
        { text: "Ramdas & Wasserman both followed", where: "author", impact: "+2.0" },
        { text: "Subscription 'e-values anytime valid' matched", where: "abstract", impact: "+1.8" },
      ],
      status: "deep",
    },
    {
      id: "p7", rank: 7, score: 6.4,
      title: "Stability of Stochastic Gradient Descent with Momentum: A Coupling Approach",
      authors: "P. Bartlett, O. Bousquet, M. Hardt",
      venue: "arXiv · stat.ML", date: "Apr 20",
      summary: "Uses a coupling argument to prove uniform stability bounds for SGD with momentum, matching lower bounds up to constants.",
      tags: ["SGD", "stability", "generalization"],
      reasons: [{ text: "Author P. Bartlett is followed", where: "author", impact: "+1.4" }],
      status: "inbox",
    },
    {
      id: "p8", rank: 8, score: 6.1,
      title: "Distribution-free Predictive Inference under Concept Drift via Online Calibration",
      authors: "I. Gibbs, E. J. Candès",
      venue: "arXiv · stat.ML", date: "Apr 20",
      summary: "Introduces an online recalibration procedure that maintains marginal coverage under arbitrary concept drift with regret bounds in O(sqrt(T)).",
      tags: ["online", "conformal", "drift"],
      reasons: [{ text: "Candès followed · 'concept drift' keyword", where: "abstract", impact: "+1.9" }],
      status: "inbox",
    },
  ],

  // ---- Queue ----
  queueSections: [
    { id: "skim",    label: "Skim Later", count: 6,  color: "accent",
      desc: "Triage pass. 5–10 min reads to decide keep/drop." },
    { id: "deep",    label: "Deep Read",  count: 5,  color: "sage",
      desc: "Scheduled for focused reading. Note-taking expected." },
    { id: "reading", label: "Reading now",count: 2,  color: "gold",
      desc: "Currently open — pinned in Reading app." },
    { id: "archived",label: "Archived",   count: 1,  color: "ink-muted",
      desc: "Finished or parked. Still searchable." },
  ],

  // ---- Library: collections ----
  collections: [
    { id: "c1", name: "Conformal Prediction under Shift", papers: 34, updated: "2d", lead: "primary thread · 12 notes", hot: true,
      seed: "finite-sample conformal under covariate shift",
      desc: "Finite-sample coverage guarantees without density ratio estimation. Includes 2024 NeurIPS survey + follow-ups." },
    { id: "c2", name: "Selective / Post-selection Inference", papers: 21, updated: "1w", lead: "reading notes 8",
      seed: "post-selection inference neural networks",
      desc: "Methods for valid inference after data-driven model choice. Bridges classical selective inference and modern BNNs." },
    { id: "c3", name: "Double Descent & Benign Overfitting", papers: 18, updated: "3d", lead: "6 annotated PDFs",
      seed: "double descent benign overfitting minimum norm",
      desc: "Theory of overparametrized regression and interpolating estimators. Focus on bias-variance tradeoffs." },
    { id: "c4", name: "E-values & Anytime-valid Testing", papers: 14, updated: "4d", lead: "3 open threads",
      seed: "e-values anytime valid inference",
      desc: "Sequential testing via martingale / e-value constructions. Includes Ramdas/Wasserman line of work." },
    { id: "c5", name: "Sparse High-dim Inference", papers: 27, updated: "2w", lead: "stable",
      seed: "sparse high-dimensional inference debiased lasso",
      desc: "Debiased lasso, confidence intervals in p >> n. Classical reference stack." },
  ],

  // ---- Monitor: authors / venues / subs ----
  authors: [
    { name: "Emmanuel J. Candès", aff: "Stanford · Statistics", newHits: 3, spark: [2,4,1,3,5,2,6] },
    { name: "Rina Foygel Barber", aff: "U. Chicago · Statistics", newHits: 1, spark: [1,2,2,1,3,2,4] },
    { name: "Ryan J. Tibshirani",  aff: "CMU / Berkeley", newHits: 2, spark: [3,2,1,4,2,5,3] },
    { name: "Aaditya Ramdas",      aff: "CMU · Statistics", newHits: 1, spark: [0,1,2,1,3,2,2] },
    { name: "Larry Wasserman",     aff: "CMU · Statistics", newHits: 0, spark: [2,3,2,1,0,1,0] },
    { name: "Trevor Hastie",       aff: "Stanford · Statistics", newHits: 2, spark: [1,0,2,3,1,4,2] },
  ],
  venues: [
    { name: "Annals of Statistics", issue: "52(2) · Apr", newHits: 4, status: "fresh" },
    { name: "JRSS-B",               issue: "86(1) · Mar", newHits: 2, status: "fresh" },
    { name: "JASA · T&M",           issue: "119 · Mar",   newHits: 1, status: "fresh" },
    { name: "Biometrika",           issue: "111(1)",      newHits: 0, status: "stable" },
    { name: "JMLR",                 issue: "rolling",     newHits: 3, status: "fresh" },
  ],
  subscriptions: [
    { name: "finite-sample conformal under shift",       hits: 7,  lastHit: "today" },
    { name: "e-values anytime valid inference",          hits: 2,  lastHit: "today" },
    { name: "double descent bias-variance",              hits: 4,  lastHit: "yesterday" },
    { name: "minimax rates nonparametric regression",    hits: 1,  lastHit: "today" },
    { name: "post-selection inference BNN",              hits: 3,  lastHit: "2d ago" },
    { name: "calibrated LLM uncertainty",                hits: 2,  lastHit: "today" },
  ],
};
